### ISSUE TITLE
Faster json decoding given the field to be extracted

### ISSUE THREAD

**Issue by teraPacket** [xiaost/jsonport#1]
Thanks for creating the jsonport! I love its simplicity and elegance.  I know it's not meant for performance testing, but I did it anyway,  the following codesnippet runs 3.1 secs on my Corei7 processor (an old one).  That means decoding and retrieving the field cost about 31us (there are 100000 loops). 

Just curious if you happen to know whether there is a faster decoding of JSON giving the json field to be retrieved (specified in the form of path,  like ["subobj", "subsubobj", "array", 1] in this case).  Logically speaking, if the decoder has the knowledge which fields are interesting, it can optimize by skipping some of uninteresting fields and hene it can be much faster.   Thoughts?

Thanks.

```go
package main

import "time"
import (
    "fmt"
    "github.com/xiaost/jsonport"
)

func main() {
	jsonstr := `{
	"foo": 1,
	"bar": 2,
	"test": "Hello, world!",
	"baz": 123.1,
	"array": [
		{"foo": 1},
		{"bar": 2},
		{"baz": 3}
	],
	"subobj": {
		"foo": 1,
		"subarray": [1,2,3],
		"subsubobj": {
			"bar": 2,
			"baz": 3,
			"array": ["hello", "world"]
		}
	},
	"bool": true
}`;
    var x string
    var err error
    sum := 1
	t0 := time.Now()
	for sum < 100000 {
    j, _ := jsonport.Unmarshal([]byte(jsonstr))
		x, err = j.GetString("subobj", "subsubobj", "array", 1)
		sum += 1
	}
	t1 := time.Now()
	fmt.Printf("The call took %v to run.\n", t1.Sub(t0))
    // Output: Tom
    fmt.Println(x)
}
```

**Comment by xiaost** [comment]
thank you for the reporting . I will look into it in a few days.

**Comment by teraPacket** [comment]
Thank you @xiaost!

**Comment by xiaost** [comment]
hi @capstar . it spent most of time in `jsonport.Unmarshal` . 
Unmarshaling with interface{} is evil. You can only define few interface{} fields only, like:
```go
type Resp struct {
    FieldA string
    FieldB string
    FieldC string
    DynamicField interface{}
}
```
Unmarshal it by [encoding/json](https://golang.org/pkg/encoding/json/) and pass the `DynamicField` to [jsonport.NewJson](https://godoc.org/github.com/xiaost/jsonport#NewJson)

**Comment by xiaost** [comment]
if it not works well, it is encoding/json package performance issue 😢

**Comment by xiaost** [comment]
@capstar do you mean something like:

```go
j, _ := jsonport.UnmarshalPath([]byte(jsonstr), "subobj", "subsubobj", "array", 1)
s, _ := j.String()
```

it is an awesome idea 👍

**Comment by teraPacket** [comment]
@xiaost yes, you are right, 
```
j, _ := jsonport.UnmarshalPath([]byte(jsonstr), "subobj", "subsubobj", "array", 1)
s, _ := j.String()
```
Would be nice.  Basically, I would like to be able to extract an element from JSON string with the input of path to locate the element.   This is logically possible, just curious if there is an implementation in go.

**Comment by xiaost** [comment]
@capstar The answer is yes.  I would like to implement it in 3 days 😄

**Comment by teraPacket** [comment]
@xiaost you are amazing! Thanks a lot.

**Comment by xiaost** [comment]
@capstar checkout the latest code of master branch.

I had refactor the json decoder & implemented [Unmarshal ](https://godoc.org/github.com/xiaost/jsonport#Unmarshal)with path

**Comment by teraPacket** [comment]
Thanks @xiaost, your updated API gave me an big speed up. It's now more than twice as fast!  Great work.  Published the gist here https://gist.github.com/capstar/f02b6b3eaccedd1396add7f1a2b65ee1
